//default import as const Cart....... export default Cart.....
export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    CLEAR_CART: 'CLEAR_CART',

    FETCH_CART_START: 'FETCH_CART_START',
    FETCH_CART_SUCCESS: 'FETCH_CART_SUCCESS',
    FETCH_CART_FAILURE: 'FETCH_CART_FAILURE',

    CART_HISTORY_UPDATE_SUCCESS: 'CART_HISTORY_UPDATE_SUCCESS'
}