export const OrderActionTypes = {
    FETCH_ORDER: 'FETCH_ORDER',
    FETCH_ORDER_SUCCESS: 'FETCH_ORDER_SUCCESS',
    FETCH_ORDER_FAILURE: 'FETCH_ORDER_FAILURE',

    CLEAR_ORDER_HISTORY: 'CLEAR_ORDER_HISTORY'
}